name: Generate R files from JSON Schema

on:
  push:
    branches:
      - main
      - brapi-V*
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      skip_job: ${{ steps.skip.outputs.skip_job }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4      
      - name: Check last commit message
        id: commit-message
        run: |
          echo "COMMIT_MESSAGE=$(git log -1 --pretty=format:'%s')" >> "$GITHUB_ENV"
      - id: skip
        name: Skip if automated push
        if: startsWith(env.COMMIT_MESSAGE, 'GitHub Action')
        run: |
          echo "Automated commit detected - skipping job"
          echo "skip_job=true" >> "$GITHUB_OUTPUT"
  build:
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.skip_job != 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          path: main

      - name: Set BrAPI branch
        id: set-brapi-branch
        run: |
          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            echo "BRAPI_BRANCH=" >> "$GITHUB_ENV"
          elif [[ "${GITHUB_REF##*/}" == brapi-V* ]]; then
            echo "BRAPI_BRANCH=${GITHUB_REF##*/}" >> "$GITHUB_ENV"
          else
            echo "BRAPI_BRANCH=" >> "$GITHUB_ENV"
          fi

      - name: Checkout BrAPI repo to temp directory
        uses: actions/checkout@v4
        with:
          repository: plantbreeding/BrAPI
          path: BrAPI
          ref: ${{ env.BRAPI_BRANCH }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Change wrapper permissions
        working-directory: ./main/generator
        run: chmod +x ./gradlew

      - name: Generate R Code
        working-directory: ./main/generator
        run: ./gradlew generateR

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install devtools
        working-directory: ./main/pkg
        run: Rscript -e "install.packages('devtools', repos = 'https://cloud.r-project.org')"

      - name: Run devtools::check
        working-directory: ./main/pkg
        run: Rscript -e "devtools::check()"

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: main
          commit_message: GitHub Action - Generate R files from JSON Schema
          file_pattern: main/**
