name: Generate R files from JSON Schema

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      skip_job: ${{ steps.skip.outputs.skip_job }}
      skip_commit: ${{ steps.check-tag.outputs.skip_commit }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4      
      - name: Check last commit message
        id: commit-message
        run: |
          echo "COMMIT_MESSAGE=$(git log -1 --pretty=format:'%s')" >> "$GITHUB_ENV"
      - id: skip
        name: Skip if automated push
        if: contains(env.COMMIT_MESSAGE, 'Apply automatic changes')
        run: |
          echo "Automated commit detected - skipping job"
          echo "skip_job=true" >> "$GITHUB_OUTPUT"
      - name: Check Branch with Regex
        id: check-tag
        run: |
          regex="^refs/heads/brapi-V[0-9]+\.[0-9]+$"
          if [[ "${{ github.ref }}" =~ $regex ]]; then
            echo "skip_commit=false" >> "$GITHUB_OUTPUT"
            echo "Release branch - WILL commit of generated files"
          else
            echo "skip_commit=true" >> "$GITHUB_OUTPUT"
            echo "Normal branch - Will NOT commit of generated files"
          fi
  generate:
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.skip_job != 'true'
    steps:
      - name: debug
        run: |
          echo ${{ needs.check.outputs.skip_job }} 
          echo ${{ needs.check.outputs.skip_commit }} 
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          path: main
      - name: Checkout BrAPI repo to temp directory
        uses: actions/checkout@v4
        with:
          repository: plantbreeding/BrAPI
          path: BrAPI
      - name: Change wrapper permissions
        working-directory: ./main/generator
        run: chmod +x ./gradlew
      - name: Generate R Code
        working-directory: ./main/generator
        run: ./gradlew generate
      - if: needs.check.outputs.skip_commit == 'false'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: main
          commit_message: Apply automatic changes
          file_pattern: main/**
